config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'search/search'
  root 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :products do
   resource :favorites, only: [:create, :destroy]
   resources :product_comments, only: [:create, :destroy]
  end
  get 'favorite/index' => 'favorites#index', as: 'favorite_index'
  get 'user/my_page' => 'users#my_page' , as: 'user_my_page'
  get 'user/mode_select/:id' => 'users#mode_select', as: 'user_mode_select'
  patch 'users/mode_change/:id' => 'users#mode_change', as: 'user_mode_change'
  patch 'product/hideen_change/:id' => 'products#hideen_change', as: 'product_hidden_change'
  get 'search' => 'search#search'
  get   'inquiry' => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
         
  scope :designer, -> { where(is_designer: "true") }
  
  has_many :products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :product_comments, dependent: :destroy
  
  validates :name, presence: true, length: { in: 2..20 } 
  validates :introduction, length: { maximum: 300 }
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.designer.page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user
      @products = @user.products
    else
      @products = @user.products.exposed
    end
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザ情報を更新しました"
      redirect_to user_my_page_path(@user)
    else
      render 'edit'
    end
  end

  def my_page
  end
  
  def mode_select
  end

  def mode_change
    if current_user.is_designer == false
      current_user.update(is_designer: true)
      flash[:notice] = "designerモードに変更しました。空白の項目がある場合は入力をしてください"
    else
      current_user.update(is_designer: false)
      flash[:notice] = "viewerモードに変更しました"
    end
    redirect_to user_my_page_path(current_user)
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :nickname, :introduction, :image, :is_designer, :homepage, :instagram, :email, :user_id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <div class="page-header">
      <h1>登録情報編集</h1>
    </div>
    <%= form_with model:@user, url:user_path(@user), method: :patch, local:true do |f| %>
    <%= render "layouts/error_message", model: f.object %>
      <div class="field">
        <%= f.label :イメージ画像 %>
        <%= attachment_image_tag current_user, :image, fallback: 'no_image.jpg', onChange: "$('.img_field').()", class: 'center-block img_prev',:size =>'400x400'%>
        <%= f.attachment_field :image, class: 'img_field' %>
      </div>
      <div class = "field row">
        <%= f.label :名前 %>
        <%= f.text_field :name, class: 'col-xs-12'%>
      </div>
      <div class = "field row">
        <%= f.label :活動名・ブランド名%>
        <%= f.text_field :nickname, class: 'col-xs-12' %>
      <div class = "field row">
        <%= f.label :紹介文%>
        <%= f.text_area :introduction, class: 'col-xs-12'%>
      </div>
      <div class = "field row">
        <%= f.label :ホームページ%>
        <%= f.text_field :homepage, class: 'col-xs-12'%>
      </div>
      <div class = "field row">
        <%= f.label :インスタグラム%>
        <%= f.text_field :instagram, class: 'col-xs-12'%>
      </div>
      <p> ※ URLは商品、及びプロフィール画面にリンクとして表示されます。
      お間違いの無いようご注意ください</p>
      <div class="actions row">
        <%= f.submit '編集内容を保存する' ,class:"btn btn-primary col-xs-12"%>
      </div>
    <% end %>
    <div class = "actions row">
      <p>※ユーザモードの切り替えにつきましては以下⇩のリンクからお願いします</p>
      <%= link_to 'ユーザモード切り替えページへ', user_mode_select_path,class:"btn btn-primary col-xs-12"%>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8" >
      <div class="page-header">
        <h1>
        <% if params[:user_id] %>
          <%= @user.name %>ページ
        <% else %>
          デザイナー一覧
        <% end %>
        </h1>
      </div>
      <div class="index-box">
        <% @users.each do |user| %>
        <div class = "index-inline-box">
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :image, :limit, 100,100, format: 'jpeg', fallback: 'no_image.jpg',size: "200x200" %><br>
            <%= user.name %>
          <% end %>
        </div>
        <% end %>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/users/mode_select.html.erb
<div class = 'container mode-select'>
  <div class="page-header">
    <h1>ユーザモード切り替え画面</h1>
  </div>
  <div class = 'mode-select-text'>
    <p class = 'caution'>！ 切り替えにあたっては必ず下記全てご確認をお願いします ！</p>
    <%if current_user.is_designer? == false%>
      <p><%="現在 #{current_user.name} 様は viewerモードです"%><br>
      ・designerモードへの変更により,<br>
      デザイナー一覧ページにあなたの情報が掲載されます</p>
    <% else %>
      <%="現在 #{current_user.name} 様は designerモードです"%>
      <p>・viewerモードへの変更により
      デザイナー一覧ページにあなたの情報が掲載されなくなります<br>
      ・現在投稿されている商品は非表示モードに切り替えない限り表示され続けますのでご注意ください</p>
    <% end %>
  </div>
  <div class = 'actions'>
    <%= link_to 'モードを切り替える',user_mode_change_path(current_user), method: :patch, data: { confirm: "【確認】モードの変更を行います。" },class:"btn btn-primary"%>
  </div>
</div>

app/views/users/my_page.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-6 col-md-offset-3'>
      <%= flash[:notice] %>
      <div class="page-header">
        <h1>マイページ</h1>
      </div>
        <%if current_user.is_designer? == false%>
         <%="現在 #{current_user.name} 様は viewerモードです"%>
        <% else %>
         <%="現在 #{current_user.name} 様は designerモードです"%>
          <% if !current_user.nickname.present?%>
          <p> ・活動名 / ブランド名があれば登録してみましょう</p>
          <%end%>
          <% if !current_user.introduction.present?%>
          <p> ・自己紹介文を登録してみましょう</p>
          <%end%>
          <% if !current_user.image.present?%>
          <p> ・イメージ写真を登録してみましょう</p>
          <%end%>
          <% if !current_user.homepage.present?%>
          <p> ・HPがあればリンクを登録してみましょう </p>
          <%end%>
          <% if !current_user.instagram.present?%>
          <p> ・instagramがあればリンクを登録してみましょう </p>
          <%end%>
        <% end %>
      </div>
    </div>
    <div class="col-md-4 col-md-offset-1">
      <div class = "my-image">
        <%= attachment_image_tag current_user, :image, fallback: "no_image.jpg",:size =>'400x400'%>
      </div>
    </div>
    <div class="col-md-4 col-md-offset-1">
      <table class = "table">
        <tbody>
          <tr>
            <th class="table-heading">名前</th>
            <td><%=current_user.name%></td>
          </tr>
          <tr>
            <th class="table-heading">活動名 / ブランド名</th>
            <% if current_user.nickname.present?%>
              <td><%=current_user.nickname%></td>
            <% else %>
              <td>（未設定）</td>
            <% end %>
          </tr>
          <tr>
            <th class="table-heading">メールアドレス</th>
            <td><%=current_user.email%></td>
          </tr>
          <tr>
            <th class="table-heading">HP</th>
            <% if current_user.homepage.present?%>
              <td><%=current_user.homepage%></td>
            <% else %>
              <td>（未設定）</td>
            <% end %>
          </tr>
          <tr>
            <th class="table-heading">instagram <i class="fab fa-instagram"></i></th>
            <% if current_user.instagram.present?%>
              <td><%=current_user.instagram%></td>
            <% else %>
              <td>（未設定）</td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
    
    <div class='col-md-6 col-md-offset-3 introduction'>
      <% if current_user.introduction.present?%>
        <%=current_user.introduction%>
      <% else %>
        紹介文　（未設定）
      <% end %>
    </div>
    
    <div class="col-md-offset-2 col-md-8 mylink-box">
      <%= link_to new_product_path,data: {"turbolinks" => false} do%>
        <div class = "my-link">
          <p class = "my-link-contents">商品新規登録</p>
        </div>
      <% end %>
      <%= link_to edit_user_path(current_user),data: {"turbolinks" => false}  do%>
        <div class = "my-link">
          <p class = "my-link-contents">登録情報編集</p>
        </div>
      <% end %>
      <%= link_to user_mode_select_path(current_user) do%>
        <div class = "my-link">
          <p class = "my-link-contents">モード変更</p>
        </div>
      <% end %>
      <%= link_to user_path(current_user) do%>
        <div class = "my-link">
          <p class = "my-link-contents">詳細/商品一覧</p>
        </div>      
      <% end %>
      <%= link_to favorite_index_path(user_id: current_user.id) do%>
        <div class = "my-link">
          <p class = "my-link-contents">お気に入り一覧</p>
        </div>   
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-1">
      <table class="table">
      <tr>
        <th><%= attachment_image_tag @user, :image, :limit, 300, 300, fallback: "no_image.jpg",size: "320x320" %></th>
        </tr>
      </table>
    </div>

    <div class="col-md-4 col-md-offset-1">
      <table class="table">
        <tr>
          <th class = "show-name"><%= @user.name %></th>
        </tr>
        <tr>
          <%if @user.nickname.present?%>
            <th>活動名 / ブランド名:<%= @user.nickname %></th>
          <% end %>
        </tr>
        <tr>
          <%if @user.introduction.present?%>
            <th><%= @user.introduction %></th>
          <% else %>
            <th>！紹介文は未登録です</th>
          <% end %>
        </tr>
        <%if @user.homepage.present?%>
          <tr>
            <th>HP : <%= link_to"#{@user.homepage}", "#{@user.homepage}"%></th>
          <tr>
          <% end %>
          <% if @user.instagram.present? %>
          <tr>
            <th>instagram  <i class="fab fa-instagram"></i> : <%= link_to "#{@user.instagram}","#{@user.instagram}"%></th>
          </tr>
          <% end %>
          <%if !(@user.homepage.present? || @user.instagram.present?)%>
          <tr>
            <th>！リンクは未登録です</th>
          </tr>
          <% end %>
        </tr>
      </table>
    </div>
    
    <div class="col-md-offset-2 col-md-8">
      <div class="page-header">
        <h3>このユーザの商品一覧</h3>
      </div>
      <%if @products.empty? %>
        <p>登録済の商品はありません</p>
      <% else %>
        <div class="index-box">
          <% @products.each do |product| %>
            <div class = "index-inline-box">
              <%= link_to product_path(product.id) do %>
                <%= attachment_image_tag product, :image, :limit, 100,100, format: 'jpeg', fallback: 'no_image.jpg',size: "200x200" %><br>
                <%= product.name %><br>
                <%= product.price %>円<br>
                <%=render 'layouts/tag_list', tag_list: product.tag_list%>
              <% end %>
            </div>
          <%end%>
        </div>
      <% end %>
    </div>
  </div>
</div>