config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'search/search'
  root 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :products do
   resource :favorites, only: [:create, :destroy]
   resources :product_comments, only: [:create, :destroy]
  end
  get 'favorite/index' => 'favorites#index', as: 'favorite_index'
  get 'user/my_page' => 'users#my_page' , as: 'user_my_page'
  get 'user/mode_select/:id' => 'users#mode_select', as: 'user_mode_select'
  patch 'users/mode_change/:id' => 'users#mode_change', as: 'user_mode_change'
  patch 'product/hideen_change/:id' => 'products#hideen_change', as: 'product_hidden_change'
  get 'search' => 'search#search'
  get   'inquiry' => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  validates :message, :presence => {:message => 'お問い合わせ内容を入力してください'}
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))    
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/inquiry/confirm.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <div class="page-header">
      <h1>お問い合わせ</h1>
    </div>
    <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
      <table class="table">
        <tr>
          <th>名前</th>
          <td>
            <%= f.hidden_field :name %>
            <%= @inquiry.name %>
          </td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td>
            <%= f.hidden_field :email %>
            <%= @inquiry.email %>
          </td>
        </tr>
        <tr>
          <th>お問い合わせ内容</th>
          <td>
            <%= f.hidden_field :message %>
            <%= simple_format(@inquiry.message) %>
          </td>
        </tr>
      </table>
      <%= f.submit '送信', data: { confirm: "【確認】以下の内容で問合せを行います。" }, :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/inquiry/index.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>    
    <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
      <div class="page-header">
        <h1>お問い合わせ</h1>
      </div>
      <% if @inquiry.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <strong>入力内容にエラーがあります</strong>
          <ul>
            <% @inquiry.errors.each do |attr, msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <table class="table">
        <tr>
          <th>名前<span class="text-danger">（必須）</span></th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th>メールアドレス<span class="text-danger">（必須）</span></th>
          <td><%= f.text_field :email %></td>
        </tr>
        <tr>
          <th>お問い合わせ内容</th>
          <td><%= f.text_area :message %></td>
        </tr>
      </table>
      <%= f.submit '確認', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/inquiry/thanks.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <div class="page-header">
      <h1>お問い合わせ</h1>
    </div>
    <p>お問い合わせいただきありがとうございました !</p>
  </div>
</div>    