config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'search/search'
  root 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :products do
   resource :favorites, only: [:create, :destroy]
   resources :product_comments, only: [:create, :destroy]
  end
  get 'favorite/index' => 'favorites#index', as: 'favorite_index'
  get 'user/my_page' => 'users#my_page' , as: 'user_my_page'
  get 'user/mode_select/:id' => 'users#mode_select', as: 'user_mode_select'
  patch 'users/mode_change/:id' => 'users#mode_change', as: 'user_mode_change'
  patch 'product/hideen_change/:id' => 'products#hideen_change', as: 'product_hidden_change'
  get 'search' => 'search#search'
  get   'inquiry' => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'
end

app/models/product.rb
class Product < ApplicationRecord
  attachment :image
  acts_as_taggable
  belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :product_comments, dependent: :destroy
	
  validates :name, presence: true,length: { in: 1..20 } 
  validates :explanation, presence: true ,length: { in: 2..300 } 
  validates :price, presence: true ,length: { in: 1..6 } ,numericality: true
  validates :image, presence: true
  
  scope :pierce,-> { where(is_pierce: "true") }
  scope :nonhole_pierce,-> { where(is_pierce: "false") }
  scope :sold_one,-> { where(is_sold_one: "true") }
  scope :allergiefree, -> { where(is_allergiefree: "true")}
  scope :hidden, -> { where(is_hidden: "true") }
  scope :exposed, -> { where(is_hidden: "false") }
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 before_action :ensure_correct_user, only: [:edit, :update, :destroy, :hideen_change]
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      flash[:notice] = "商品を登録しました"
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end
  
  def index
    if params[:tag_name]
      @products = Product.exposed.tagged_with("#{params[:tag_name]}").page(params[:page]).per(15)
    elsif params[:is_pierce] == "true"
      @products = Product.exposed.pierce.page(params[:page]).per(15)
      @word = 'ピアス'
    elsif params[:is_pierce] == "false"
      @products = Product.exposed.nonhole_pierce.page(params[:page]).per(15)
      @word = 'イヤリング'
    elsif params[:is_allergiefree] == "true"
      @products = Product.exposed.allergiefree.page(params[:page]).per(15)
      @word = 'アレルギーフリー商品'
    elsif params[:is_sold_one] == "true"
      @products = Product.exposed.sold_one.page(params[:page]).per(15)
      @word = '片方のみ販売可能商品'
    else
      @products = Product.exposed.page(params[:page]).per(15)
      @word = '全商品'
    end
  end

  def show
    @product = Product.find(params[:id])
    user = @product.user
    random = "RANDOM()"
    if Rails.env.production?
      random = "rand()"
    end
    @products = user.products.exposed.where.not(id:@product.id).order(random).limit(3)
    # @products = user.products.exposed.where.not(id:@product.id).order("RANDOM()").limit(3)
    @product_comment = ProductComment.new
  end

  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "商品情報を更新しました"
      redirect_to product_path(params[:id])
    else
      render 'edit'
    end
  end
  
  def destroy
    @product.destroy
    flash[:notice] = "商品情報を削除しました"
    redirect_to user_my_page_path(current_user)
  end
   
  def hideen_change
    product = Product.find(params[:id])
    if product.is_hidden== false
      product.update(is_hidden: true)
      flash[:notice] = "商品を非表示に設定しました"
    else
      product.update(is_hidden: true)
      flash[:notice] = "商品を表示する設定に変更しました"
    end
    redirect_to product_path(product)
  end
  
  private
  def product_params
    params.require(:product).permit(:name, :explanation, :image, :price, :is_pierce, :is_sold_one, :is_hidden, :is_allergiefree, :tag_list)
  end
  
  def ensure_correct_user
    @product = Product.find(params[:id])
    unless @product.user == current_user
      redirect_to productss_path
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comment.html.erb
<table>
  <% product.product_comments.each do |product_comment| %>
    <% product_comment_user = product_comment.user %>
    <tr>
      <td>
    		<%= link_to user_path(product_comment_user), class: "user_#{product_comment_user.id}" do %>
          <%= attachment_image_tag product_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
          <%= product_comment_user.name %>
        <% end %>
      </td>
      <td><%= product_comment.comment %></td>
      <% if current_user == product_comment_user %>
        <td><%= link_to 'Destroy', product_product_comment_path(product_comment.product_id, product_comment.id), class: 'btn-sm btn-danger', method: :delete %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/products/edit.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <div class="page-header">
      <h1>商品編集ページ</h1>
    </div>
    <%= form_with model:@product,local:true do |f| %>
    <%= render 'layouts/error_message', model: f.object %>
      <div class="field">
        <%= f.label :イメージ画像 %>
        <%= attachment_image_tag @product, :image, fallback: 'no_image.jpg', onChange: "$('.img_field').()", class: 'center-block img_prev',:size =>'400x400'%>
        <%= f.attachment_field :image, class: 'img_field' %>
      </div>
      <div class="form-group">
        <%= f.radio_button :is_pierce, false %>
        <%= f.label :イヤリング %>
        <%= f.radio_button :is_pierce, true %>
        <%= f.label :ピアス %>
      </div>
      <div class="field row">
        <%= f.label :作品名 %>
        <%= f.text_field :name, class: 'col-xs-12'%>
      </div>
      <div class="field row">
        <%= f.label :商品説明 %>
        <%= f.text_area :explanation, class: 'col-xs-12'%>
      </div>
      <div class="field row">
        <%= f.label :税抜き価格 %>（円）
        <%= f.text_field :price, class: 'col-xs-12'%>
      </div>
      <div class = "form-group">
        <%= f.label :タグ%>
         ※複数の場合はスペースをあけずに「,」区切りで入力してください
        <%= f.text_field :tag_list, value: @product.tag_list.join(','), class: 'col-xs-12'%>
      </div> 
      <div class="form-group">
        <%= f.radio_button :is_sold_one, false %>
        <%= f.label :片方のみの販売不可 %>
        <%= f.radio_button :is_sold_one, true %>
        <%= f.label :片方のみの販売可 %>
      </div>
      <div class="form-group">
        <%= f.radio_button :is_allergiefree, false %>
        <%= f.label :金属アレルギー非対応 %>
        <%= f.radio_button :is_allergiefree, true %>
        <%= f.label :金属アレルギー対応 %>
      </div>
      <div class="form-group">
        <%= f.radio_button :is_hidden, false %>
        <%= f.label :この商品を公開する %>
        <%= f.radio_button :is_hidden, true %>
        <%= f.label :この商品を非公開にする %>
      </div>
      <div class="actions row">
        <%= f.submit '商品情報を編集する',class: 'btn btn-primary col-xs-12'%>
      </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="page-header">
        <h1><%= @word%></h1>
      </div>
      <div class="index-box">
        <% @products.each do |product| %>
          <div class = "index-inline-box">
            <%= link_to product_path(product.id) do %>
              <%= attachment_image_tag product, :image, :limit, 100,100, format: 'jpeg', fallback: 'no_image.jpg',size: "200x200" %><br>
              <%= product.name %><br>
              <%= product.price %>円<br>
              <%=render 'layouts/tag_list', tag_list: product.tag_list%>
            <% end %>
          </div>
        <%end%>
        <%= paginate @products %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <div class="page-header">
      <h1>商品新規登録</h1>
    </div>
    <%= form_with model:@product,local:true do |f| %>
    <%= render "layouts/error_message", model: f.object %>
      <div class="field">
       <%= f.label :イメージ画像 %>
       <%= attachment_image_tag @product, :image, fallback: 'no_image.jpg', onChange: "$('.img_field').()", class: 'center-block img_prev',:size =>'400x400'%>
      <%= f.attachment_field :image, class: 'img_field' %>
      </div>
      <div class="form-group">
        <%= f.radio_button :is_pierce, false %>
        <%= f.label :イヤリング %>
        <%= f.radio_button :is_pierce, true %>
        <%= f.label :ピアス %>
      </div>
      <div class="field row">
        <%= f.label :商品名 %>
        <%= f.text_field :name,class: "form-control" %>
      </div>
      <div class="field row">
        <%= f.label :商品説明 %>
        <%= f.text_area :explanation, class: "form-control"%>
      </div>
      <div class="field row">
        <%= f.label :税抜き価格 %>
        <%= f.text_field :price, class: "form-control"%>
      </div>
      <div class = "form-group">
        <%= f.label :タグ%>
         ※複数の場合はスペースをあけずに「,」区切りで入力してください
        <%= f.text_field :tag_list, value: @product.tag_list.join(','), class: "form-control"%>
      </div> 
      <div class="form-group">
        <%= f.radio_button :is_sold_one, false %>
        <%= f.label :片方のみの販売不可 %>
        <%= f.radio_button :is_sold_one, true %>
        <%= f.label :片方のみの販売可 %>
      </div>
      <div class="form-group">
        <%= f.radio_button :is_allergiefree, false %>
        <%= f.label :金属アレルギー非対応 %>
        <%= f.radio_button :is_allergiefree, true %>
        <%= f.label :金属アレルギー対応 %>
      </div>
      <div class="form-group">
        <%= f.radio_button :is_hidden, false %>
        <%= f.label :この商品を公開する %>
        <%= f.radio_button :is_hidden, true %>
        <%= f.label :この商品を非公開にする %>
      </div>
      <div class="actions row">
        <%= f.submit '商品を登録する', class: 'btn btn-primary col-xs-12'%>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-1">
      <%= flash[:notice] %>
      <table class="table">
        <tr>
          <th><%= attachment_image_tag @product, :image, :limit, 300, 300, fallback: "no_image.jpg",size: "320x320" %></th>
        </tr>
      </table>
    </div>
    <div class="col-md-4 col-md-offset-1">
      <table class="table">
        <tr>
          <th class = "show-name"><%= @product.name %></th>
        </tr>
        <tr>
          <% if @product.user.is_designer?%>
            <th>作家名 : <%= link_to"#{@product.user.name}",user_path(@product.user) %></th>
          <% else %>
            <th>作家名 : <%=@product.user.name %></th>
          <% end %>
        </tr>
        <tr>
          <%if @product.user.nickname.present?%>
            <th>活動名 / ブランド名 :<%= @product.user.nickname %></th>
          <% end %>
        </tr>
        <tr>
          <th><%= @product.explanation%></th>
        </tr>
        <tr>
          <th>商品価格(税抜): <%= @product.price%>円</th>
        </tr>
        <tr>
          <th>
            <% if @product.is_pierce %>
            カテゴリ : ピアス
            <% else %>
            カテゴリ : イヤリング
            <% end %>
          </th>
        </tr>
        <tr>
          <th>
            <% if @product.is_sold_one %>
            片方のみの販売 : 可
            <% else %>
            片方のみの販売 : 不可
            <% end %>
          </th>
        </tr>
        <% if @product.is_allergiefree %>
          <tr>
            <th>※ 金属アレルギー対応商品</th>
          </tr>
        <% end %>
        <% if @product.user.homepage.present?%>
          <tr>
            <th>HP : <%=link_to "#{@product.user.homepage}", "#{@product.user.homepage}"%></th>
          </tr>
        <% end %>
        <% if @product.user.instagram.present?%>
          <tr>
            <th>instagram <i class="fab fa-instagram"></i> : <%=link_to "#{@product.user.instagram}", "#{@product.user.instagram}"%></th>
          </tr>
        <% end %>
        <%if @product.user == current_user%>
        <tr>
          <th>
            <% if @product.is_hidden %>
            表示モード : 非表示
            <% else %>
            表示モード : 表示中
            <% end %>
          </th>
        </tr>
        <%end%>
    
        <%if !@product.tag_list.empty? %>
          <tr>
            <th>タグ : <%=render 'layouts/tag_list', tag_list: @product.tag_list%></th>
          </tr>
        <% end %>
        
        <th id="product_<%= @product.id %>">
          <span class="favorite-btn"><%= render "favorites/favorite-btn", product: @product %></soan>
        </th>
        </tr>
      </table>
      <% if @product.user == current_user %>
      <%= link_to "編集する",edit_product_path(@product.id),class: "btn btn-primary" ,data: {"turbolinks" => false}%>
      <%= link_to "削除する",product_path(@product.id) ,method: :delete, "data-confirm" => "本当に削除しますか？（この操作は取り消せません）", class:"btn btn-danger"%>
      <% end %>
    </div>
  </div>
  
  <div>
    <h2>投稿する</h2>
    <%= form_with model:[@product,@product_comment],local:true do |f| %>
      <div class="field row">
        <%= f.label :コメント %>
        <%= f.text_area :comment, class: "form-control"%>
      </div>
      <div class="actions row">
        <%= f.submit 'コメントを登録する', class: 'btn btn-primary col-xs-12'%>
      </div>
    <% end %>
  </div>  
  <%= render 'products/comment' , product: @product%>
  
    <% if @product.user.products.exposed.count >= 2 %>
      <div class="col-md-offset-2 col-md-8">
        <div class="page-header">
          <h3>このユーザはこんな商品も登録しています</h3>
        </div>
        <div class="index-box">
          <% @products.each do |product|%>
            <div class = "index-inline-box">
              <%= link_to product_path(product.id) do %>
                <%= attachment_image_tag product, :image, :limit, 100,100, format: 'jpeg', fallback: 'no_image.jpg',size: "200x200" %><br>
                <%= product.name %><br>
                <%= product.price %>円<br>
                <%=render 'layouts/tag_list', tag_list: product.tag_list%>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>