config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'search/search'
  root 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :products do
   resource :favorites, only: [:create, :destroy]
   resources :product_comments, only: [:create, :destroy]
  end
  get 'favorite/index' => 'favorites#index', as: 'favorite_index'
  get 'user/my_page' => 'users#my_page' , as: 'user_my_page'
  get 'user/mode_select/:id' => 'users#mode_select', as: 'user_mode_select'
  patch 'users/mode_change/:id' => 'users#mode_change', as: 'user_mode_change'
  patch 'product/hideen_change/:id' => 'products#hideen_change', as: 'product_hidden_change'
  get 'search' => 'search#search'
  get   'inquiry' => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end
# 「bin/rails g active_admin:resource User」コマンドで生成。activeadminで、userを扱えるようにした

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
	belongs_to :product
	
	scope :only_exposed, -> {joins(:product).merge(Product.exposed)}
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  validates :message, :presence => {:message => 'お問い合わせ内容を入力してください'}
end

app/models/part.rb
class Part < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  attachment :image
  acts_as_taggable
  belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :product_comments, dependent: :destroy
	
  validates :name, presence: true,length: { in: 1..20 } 
  validates :explanation, presence: true ,length: { in: 2..300 } 
  validates :price, presence: true ,length: { in: 1..6 } ,numericality: true
  validates :image, presence: true
  
  scope :pierce,-> { where(is_pierce: "true") }
  scope :nonhole_pierce,-> { where(is_pierce: "false") }
  scope :sold_one,-> { where(is_sold_one: "true") }
  scope :allergiefree, -> { where(is_allergiefree: "true")}
  scope :hidden, -> { where(is_hidden: "true") }
  scope :exposed, -> { where(is_hidden: "false") }
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/product_comment.rb
class ProductComment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :product
  belongs_to :tag
  validates :product_id,presence:true
  validates :tag_id,presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
         
  scope :designer, -> { where(is_designer: "true") }
  
  has_many :products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :product_comments, dependent: :destroy
  
  validates :name, presence: true, length: { in: 2..20 } 
  validates :introduction, length: { maximum: 300 }
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    #@products = Product.exposed.order("RANDOM()")
    random = "RANDOM()"
    if Rails.env.production?
      random = "rand()"
    end
    @products = Product.exposed.order(random)
    @tags = Product.exposed.all_tags.order(random).limit(20).pluck(:name)
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))    
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @datas = search_for(@model, @content)
  end

  private
  def partical(model, content)
    if model == 'user'
      User.designer.where("name LIKE ?", "%#{content}%").page(params[:page]).per(15)
    elsif model == 'product'
      Product.exposed.where("name LIKE ?", "%#{content}%").page(params[:page]).per(15)
    end
  end

  def search_for(model, content)
    partical(model, content)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.designer.page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user
      @products = @user.products
    else
      @products = @user.products.exposed
    end
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザ情報を更新しました"
      redirect_to user_my_page_path(@user)
    else
      render 'edit'
    end
  end

  def my_page
  end
  
  def mode_select
  end

  def mode_change
    if current_user.is_designer == false
      current_user.update(is_designer: true)
      flash[:notice] = "designerモードに変更しました。空白の項目がある場合は入力をしてください"
    else
      current_user.update(is_designer: false)
      flash[:notice] = "viewerモードに変更しました"
    end
    redirect_to user_my_page_path(current_user)
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :nickname, :introduction, :image, :is_designer, :homepage, :instagram, :email, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
  <div id="error-explanation" class="alert alert-danger">
    <h2><%= model.errors.count %>件のエラーが発生しました</h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_tag_list.html.erb
<% tag_list.each do |tag|%>
  <%= link_to tag, products_path(tag_name: tag)%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ear!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/120d3f8e53.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>
  <body>
    <header>
      <div class = "row">
        <div class = "header-item col-md-offset-2 col-md-8">
          <div class="logo"><%= link_to "ear!", root_path, class:'logolink', data: {"turbolinks" => false}%></div>
          <div class = "header-link-item">
            <% if user_signed_in? %>
              <div class = "header-link-item-list">
                <%= link_to destroy_user_session_path, method: :delete, :class => "header-link-icon" do%>
                  <i class="fas fa-sign-out-alt"></i> LOG OUT
                <% end %>
              </div>
              <div class = "header-link-item-list">
                <%= link_to user_my_page_path, :class => "header-link-icon" do%>
                  <i class="fas fa-user-circle"></i> MY PAGE
                <% end %>
              </div>
            <% else%>
              <div class = "header-link-item-list">
                <%= link_to new_user_session_path, :class => "header-link-icon" do%>
                  <i class="fas fa-sign-in-alt"></i> LOG IN
                <% end %>
              </div>
              <div class = "header-link-item-list">
                <%= link_to new_user_registration_path, :class => "header-link-icon" do%>
                  <i class="fas fa-user-plus"></i> SIGN IN
                <% end %>
              </div>
            <% end %>
            <div class = "header-link-item-list">
              <%= link_to inquiry_path, :class => "header-link-icon" do%>
                <i class="fas fa-envelope"></i> CONTACT
              <% end %>
            </div>
          </div>
          <div class="search-form">
            <%= form_tag(search_path, method: :get) do %>
              <%= text_field_tag 'search[content]' %>
              <%= select_tag 'search[model]', options_for_select({ "デザイナー" => "user", "商品名" => "product" }) %>
              <%= button_tag '<i class="fa fa-search"></i>'.html_safe, :type => "submit", :class =>"btn btn-default btn-s-md" %>
            <% end %>
          </div>
        </div>
        
        <div id="sp-menu">
          <ul>
            <li><%= link_to "デザイナー一覧", users_path%></li>
            <li><%= link_to "商品一覧", products_path %></li>
            <li><%= link_to "ピアス一覧", products_path(is_pierce: true)%></li>
            <li><%= link_to "イヤリング一覧", products_path(is_pierce: false)%></li>
            <li><%= link_to "ノンアレルギー商品", products_path(is_allergiefree: true)%></li>
            <li><%= link_to "片方のみ販売可能商品", products_path(is_sold_one: true)%></li>
          </ul>
        </div>
        <div id="hm-icon">
          <a class="menu-trigger" href="#">
            <span></span>
            <span></span>
            <span></span>
          </a>
        </div>
      </div>
    </header>
    <%= yield %>
    <script>
      $(function() {
        $('.menu-trigger').on('click', function(event) {
          $(this).toggleClass('active');
          $('#sp-menu').fadeToggle();
        event.preventDefault();
        });
      });
    </script>
  </body>
</html>